#!/bin/sh
#
# sja1105        Works around known issue of link speed auto-negotiation
#                not working on the NXP LS1021A-TSN board.
#

ETH2_SPEED_MBPS=1000
ETH3_SPEED_MBPS=1000
ETH4_SPEED_MBPS=1000
ETH5_SPEED_MBPS=1000

mbps_to_clause_22_speed() {
	# Clause 22, register 0 (MII Control register), Speed Selection bits
	# are bit 13 (LSB) and bit 6 (MSB).
	case "$1" in
	10)   echo "0"                  ;; # 0b00 => 10Mbps
	100)  echo "$((0<<6 | 1<<13))"  ;; # 0b01 => 100Mbps
	1000) echo "$((1<<6 | 0<<13))"  ;; # 0b10 => 1000Mbps
	*)    echo "invalid link speed" ;;
	esac
}

mbps_to_sja1105_speed() {
	case "$1" in
	10)   echo "0b11"               ;;
	100)  echo "0b10"               ;;
	1000) echo "0b01"               ;;
	*)    echo "invalid link speed" ;;
	esac
}

fixup_mac_link_speeds() {
	# Patch the current staging area. Operations are idempotent
	# (multiple applications have the same effect as a single one).
	sja1105-tool config modify mac[1] speed $(mbps_to_sja1105_speed ${ETH2_SPEED_MBPS})
	sja1105-tool config modify mac[2] speed $(mbps_to_sja1105_speed ${ETH3_SPEED_MBPS})
	sja1105-tool config modify mac[3] speed $(mbps_to_sja1105_speed ${ETH4_SPEED_MBPS})
	sja1105-tool config modify mac[0] speed $(mbps_to_sja1105_speed ${ETH5_SPEED_MBPS})
	# Update the configuration in the switch
	sja1105-tool config upload
}

fixup_phy_link_speeds() {
	# Clause 22, register address 0 (MII control):
	# Bit 15: RESET
	# Bit 14: LOOPBACK
	# Bit 13: SPEED_SELECT (LSB)
	# Bit 12: AUTONEG_ENABLE
	# Bit 11: POWER_DOWN
	# Bit  9: RE_AUTONEG
	# Bit  8: DUPLEX_MODE
	# Bit  6: SPEED_SELECT (MSB)
	etsec_mdio write 3 0 $((1<<15 | 1<<8 | $(mbps_to_clause_22_speed ${ETH2_SPEED_MBPS})))
	etsec_mdio write 4 0 $((1<<15 | 1<<8 | $(mbps_to_clause_22_speed ${ETH3_SPEED_MBPS})))
	etsec_mdio write 5 0 $((1<<15 | 1<<8 | $(mbps_to_clause_22_speed ${ETH4_SPEED_MBPS})))
	etsec_mdio write 6 0 $((1<<15 | 1<<8 | $(mbps_to_clause_22_speed ${ETH5_SPEED_MBPS})))
}

info() {
	echo "Setting ETH2 link speed to ${ETH2_SPEED_MBPS}"
	echo "Setting ETH3 link speed to ${ETH3_SPEED_MBPS}"
	echo "Setting ETH4 link speed to ${ETH4_SPEED_MBPS}"
	echo "Setting ETH5 link speed to ${ETH5_SPEED_MBPS}"
}

case "$1" in
start)
	info
	fixup_mac_link_speeds
	fixup_phy_link_speeds
	;;
*)
	echo "Usage: $0 start"
esac

